spring.application.name=backend-app


spring.datasource.url=jdbc:postgresql://dpg-d5f2sjp5pdvs73ft7ae0-a:5432/codetech_database
spring.datasource.username=root
spring.datasource.password=zAywmq96BURyk1vhUu4DABgfPf9HPb5d
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect